import os
import sys
import time
import winreg
import zipfile
import shutil
import winshell
import psutil
import inquirer
import colorama
import win32com.client
import selenium
import selenium.webdriver.firefox.options
import selenium.webdriver.common.by
import selenium.webdriver.support.ui
import selenium.webdriver.support.expected_conditions
import selenium.webdriver.firefox.service
